### ISSUE TITLE
Default value is not checked when enabling Build button on Build image page

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#13125]
### Bug description

It seems that the `Build` button is not enabled on the Build Image page after selecting a container file with the file picker, instead the user needs to deselect and reselect an architecture type in order for the button to be enabled.

https://github.com/user-attachments/assets/0738129e-1c35-43d3-964d-0624b02baffc

### Operating system

macOS

### Installation Method

None

### Version

1.20.0

### Steps to reproduce

1. Go to Images page.
2. Select `Build` images button.
3. Choose a container file using the file picker on the Build image page.
4. Notice that the `Build` button is not enabled, instead deselect the default architecture setting and reselect it.
5. Now the button is enabled.

### Relevant log output

```shell

```

**Comment by rujutashinde** [comment]
@cbr7 @odockal  If there is a workaround for this issue could you please add it to a comment, in case users come across this one

**Comment by cbr7** [comment]
@rujutashinde the workaround is in the video, all the user has to do is deselect the default selection and reselect it/choose some other option.

**Comment by Firewall** [comment]
@cbr7 @rujutashinde Eventhough that is a work-around... I don't think that is intuative at all and the user would probably just say its broken instead of knowing to select and deselect it.

**Comment by cbr7** [comment]
@Firewall I agree with that, although I don't consider it a blocker to the release, it certainly should be fixed sooner rather then later.

**Comment by axel7083** [comment]
Fixed by https://github.com/podman-desktop/podman-desktop/pull/13103 on main branch

**Comment by ScrewTSW** [comment]
> Fixed by [#13103](https://github.com/podman-desktop/podman-desktop/pull/13103) on main branch

Still present in v1.20.1 (linux flatpak)

https://github.com/user-attachments/assets/d7c6a305-30ab-4131-b03f-bc7461837645

**Comment by ScrewTSW** [comment]
won't fix for 1.20.x
