### ISSUE TITLE
Troubleshooting Stores page: kubernetes resources count cannot be fetched

### ISSUE THREAD

**Issue by simonrey1** [containers/podman-desktop#13470]
### Bug description

In the Troubleshooting Stores page, when clicking on refresh on the `kubernetes resources count` tile, I get the following error:

`Uncaught (in promise) Error: contextsStatesDispatcher is undefined. This should not happen in Kubernetes experimental
Promise.then
listResourcesCount @ kubernetes-resources-count.ts:49`

<img width="1454" height="1100" alt="Image" src="https://github.com/user-attachments/assets/27d833c6-0018-4909-82ee-56bb80ffa28c" />

### Operating system

Mac 15

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Open the Troubleshooting Stores page, click on refresh on the `kubernetes resources count` tile, watch for console errrors.

### Relevant log output

```shell

```

**Comment by gastoner** [comment]
Hello I think that this should be fixed by https://github.com/podman-desktop/podman-desktop/pull/13473 or https://github.com/podman-desktop/podman-desktop/pull/13225 since I don't see the error now 
cc @eqqe can you verify?

**Comment by simonrey1** [comment]
@gastoner I am still seeing the error when clicking on refresh on the `kubernetes resources count` tile.

**Comment by simonrey1** [comment]
@gastoner When enabling the experimental option `Kubernetes states Experimental`, it is working ok. Should we close this issue and leave it not working without the experimental option? 

<img width="792" height="127" alt="Image" src="https://github.com/user-attachments/assets/fa0f4298-c132-418d-aba9-38ef5876a7af" />

**Comment by gastoner** [comment]
@eqqe I think we should not see the error either if it is enabled/not enabled. And I think if we don't see it we can close it

**Comment by simonrey1** [comment]
> [@eqqe](https://github.com/eqqe) I think we should not see the error either if it is enabled/not enabled. And I think if we don't see it we can close it

When it is disabled, I can see the error in the console logs.

**Comment by feloy** [comment]
As far as I understand, in non-experimental mode:

- the `kubernetes-resources-count` store is "disabled" (by returning false in `checkForUpdate`)
- the `packages/renderer/src/lib/troubleshooting/TroubleshootingPageStore.svelte` component calls `fetch` on the store when the user clicks `Refresh`
- `fetch` does not call `checkForUpdate` to check if it is ok to update the store, and because of this, problems happen

I would not worry too much on this issue, as it is painless, and the Kubernetes experimental mode is expected to be removed soon
