### ISSUE TITLE
Compose setup fails when there is already docker-compose

### ISSUE THREAD

**Issue by marukaz** [containers/podman-desktop#5334]
### Bug description

For some reason, podman-desktop failed to find docker-compose under `/usr/local/bin/docker-compose`. I don't remember how it is installed but maybe by podman-desktop since compose extension did not show setup button.

So, I reinstalled podman-desktop and this time the setup button appeared in the compose tile.
However, when I proceed, it shows following error:

```
Unable to install docker-compose binary: Command execution failed with exit code 1: Command execution failed with exit code 1
```

After I removed `/usr/local/bin/docker-compose`, it succeeded.

### Operating system

macOS Sonoma 14.2.1 (arm)

### Installation Method

Brew (macOS)

### Version

1.6.3

**Comment by riginoommen** [comment]
I am also facing this issue

**Comment by ahmetwaly** [comment]
I faced the same issue and following @marukaz approach by removing  `/usr/local/bin/docker-compose` It worked

**Comment by cfergeau** [comment]
Still an issue with podman-desktop v1.11.1

**Comment by jeffmaury** [comment]
Fixed by 154ff70d45181d0cb78e47ce15b115d4e0ea7bf4

**Comment by kapkekes** [comment]
Hi, have faced this problem with **macOS Sonoma 14.5 (ARM)** and **Podman Desktop v1.12.0**.

I had removed Docker Desktop before setting up Podman Desktop, but it seems like Docker left some dangling symlinks, including `/usr/local/bin/docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose`.

After deleting the symlink, the Compose extension was able to install `docker-compose` to use with `podman compose`.

UPD: oh, have checked the mentioned commit; guess that fix will appear in **v1.13.0**.

**Comment by blackhelicoptersdotnet** [comment]
This is still an issue with Podman Desktop 1.13.3 on Sequoia ARM 15.0.1

Same error message, and the same fix as in the original report.

**Comment by MaurizioVacca** [comment]
This is still happening with Podman Desktop (1.14.1 - arm64) and macOS Sonoma 14.5 🥲

**Comment by shussey** [comment]
Still there in 1.14.2
Resolved on my mac by @kapkekes tip. Thanks very much

**Comment by dgolovin** [comment]
I opened PR https://github.com/podman-desktop/podman-desktop/pull/10313 to fix the issue.

**Comment by chad-vogel** [comment]
I'm having issue with in 26.0.1

**Comment by butelo** [comment]
same issue Version 1.24.2 (1.24.2) in macos tahoe 26.2

**Comment by micronetic** [comment]
Still happening with version v1.25.1 on  macOS 26.2

**Comment by ThatXliner** [comment]
Still an issue for Podman v5.8.1  Version 1.26.2 (1.26.2) macOS 15.4.1 (24E263)

**Comment by emanuelcoelho1986** [comment]
Still an issue for Podman V5.8.2 with MacOS (Version 26.4.1)
